/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Genel;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enes Behlül
 */
public class TumGiderler extends javax.swing.JFrame {

    /**
     * Creates new form TumGiderler
     */
    PrintWriter output = null;
    BufferedReader input = null;
    DefaultTableModel dtm;
    File gider;

    public TumGiderler() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Giderler");
        gider = new File("Gider.txt");
        if (gider.exists()) {
            try {
                input = new BufferedReader(new FileReader("Gider.txt"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TumGiderler.class.getName()).log(Level.SEVERE, null, ex);
            }
            String satir = null;
            dtm = new DefaultTableModel();
            dtm.setColumnIdentifiers(new String[]{"Durum", "Sıra NU.", "Tarih", "Fatura NU.", "Açıklama", "Yekün"});
            tblTumGiderler.setModel(dtm);
            while ((satir = input.readLine()) != null) {
                String[] dizi = satir.split("`");
                dtm.addRow(dizi);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTumGiderler = new javax.swing.JTable();
        btnSil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTumGiderler.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblTumGiderler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTumGiderler);

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSil)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        try {
            // TODO add your handling code here:
            if (tblTumGiderler.getSelectedRowCount() == 1) {
                output = new PrintWriter(new FileWriter("SilinenGiderler.txt", true));
                output.println(dtm.getValueAt(tblTumGiderler.getSelectedRow(), 0) + "`" + dtm.getValueAt(tblTumGiderler.getSelectedRow(), 1) + "`" + dtm.getValueAt(tblTumGiderler.getSelectedRow(), 2) + "`" + dtm.getValueAt(tblTumGiderler.getSelectedRow(), 3) + "`" + dtm.getValueAt(tblTumGiderler.getSelectedRow(), 4) + "`" + dtm.getValueAt(tblTumGiderler.getSelectedRow(), 5));
                output.close();
                dtm.removeRow(tblTumGiderler.getSelectedRow());
                output = new PrintWriter(new FileWriter("Gider.txt"));
                output.write("");
                output = new PrintWriter(new FileWriter("Gider.txt", true));
                for (int i = 0; i < tblTumGiderler.getRowCount(); i++) {
                    output.println(dtm.getValueAt(i, 0) + "`" + dtm.getValueAt(i, 1) + "`" + dtm.getValueAt(i, 2) + "`" + dtm.getValueAt(i, 3) + "`" + dtm.getValueAt(i, 4) + "`" + dtm.getValueAt(i, 5));
                }
                output.close();
                JOptionPane.showMessageDialog(rootPane, "Silme tamamlandı.");
            } else if (tblTumGiderler.getSelectedRowCount() != 0) {
                JOptionPane.showMessageDialog(rootPane, "Silmeden önce bir seçim yapmalısınız.");
            }
        } catch (IOException ex) {
            Logger.getLogger(TumGelirler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TumGiderler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TumGiderler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TumGiderler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TumGiderler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TumGiderler().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(TumGiderler.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTumGiderler;
    // End of variables declaration//GEN-END:variables
}
